export const saxoNotes = [
  {
    name: 'Do',
    audio: '/music/saxofon/do-sf.mp3',
    img: 'https://res.cloudinary.com/atusdedos/image/upload/v1665984599/saxofon/do_kdc8qc.png',
    answer1: false,
    answer2: false,
    answer3: false,
    answer4: false,
    answer5: false,
    answer6: false,
    answer7: true,
    answer8: false,
    answer9: true,
    answer10: false,
    answer11: true,
    answer12: true,
    answer13: false,
    answer14: false,
    answer15: true,
    answer16: true,
    answer17: true,
    answer18: false,
    answer19: false,
    answer20: false,
    answer21: false,
    answer22: false,
    answer23: false,
    answer24: false,
  },
  {
    name: 'Re',
    audio: '/music/saxofon/re-sf.mp3',
    img: 'https://res.cloudinary.com/atusdedos/image/upload/v1665984599/saxofon/re_t1twot.png',
    answer1: false,
    answer2: false,
    answer3: false,
    answer4: false,
    answer5: false,
    answer6: false,
    answer7: false,
    answer8: false,
    answer9: true,
    answer10: false,
    answer11: true,
    answer12: true,
    answer13: false,
    answer14: false,
    answer15: true,
    answer16: true,
    answer17: true,
    answer18: false,
    answer19: false,
    answer20: false,
    answer21: false,
    answer22: false,
    answer23: false,
    answer24: false,
  },
  {
    name: 'Mi',
    audio: '/music/saxofon/mi-sf.mp3',
    img: 'https://res.cloudinary.com/atusdedos/image/upload/v1665984599/saxofon/mi_scmsi2.png',
    answer1: false,
    answer2: false,
    answer3: false,
    answer4: false,
    answer5: false,
    answer6: false,
    answer7: false,
    answer8: false,
    answer9: true,
    answer10: false,
    answer11: true,
    answer12: true,
    answer13: false,
    answer14: false,
    answer15: true,
    answer16: true,
    answer17: false,
    answer18: false,
    answer19: false,
    answer20: false,
    answer21: false,
    answer22: false,
    answer23: false,
    answer24: false,
  },
  {
    name: 'Fa',
    audio: '/music/saxofon/fa-sf.mp3',
    img: 'https://res.cloudinary.com/atusdedos/image/upload/v1665984599/saxofon/fa_blnmlz.png',
    answer1: false,
    answer2: false,
    answer3: false,
    answer4: false,
    answer5: false,
    answer6: false,
    answer7: false,
    answer8: false,
    answer9: true,
    answer10: false,
    answer11: true,
    answer12: true,
    answer13: false,
    answer14: false,
    answer15: true,
    answer16: false,
    answer17: false,
    answer18: false,
    answer19: false,
    answer20: false,
    answer21: false,
    answer22: false,
    answer23: false,
    answer24: false,
  },
  {
    name: 'Sol',
    audio: '/music/saxofon/sol-sf.mp3',
    img: 'https://res.cloudinary.com/atusdedos/image/upload/v1665984599/saxofon/sol_musw5q.png',
    answer1: false,
    answer2: false,
    answer3: false,
    answer4: false,
    answer5: false,
    answer6: false,
    answer7: false,
    answer8: false,
    answer9: true,
    answer10: false,
    answer11: true,
    answer12: true,
    answer13: false,
    answer14: false,
    answer15: false,
    answer16: false,
    answer17: false,
    answer18: false,
    answer19: false,
    answer20: false,
    answer21: false,
    answer22: false,
    answer23: false,
    answer24: false,
  },
  {
    name: 'La',
    audio: '/music/saxofon/la-sf.mp3',
    img: 'https://res.cloudinary.com/atusdedos/image/upload/v1665984599/saxofon/la_yz8pyc.png',
    answer1: false,
    answer2: false,
    answer3: false,
    answer4: false,
    answer5: false,
    answer6: false,
    answer7: false,
    answer8: false,
    answer9: true,
    answer10: false,
    answer11: true,
    answer12: false,
    answer13: false,
    answer14: false,
    answer15: false,
    answer16: false,
    answer17: false,
    answer18: false,
    answer19: false,
    answer20: false,
    answer21: false,
    answer22: false,
    answer23: false,
    answer24: false,
  },
  {
    name: 'Si',
    audio: '/music/saxofon/si-sf.mp3',
    img: 'https://res.cloudinary.com/atusdedos/image/upload/v1665984599/saxofon/si_u7grsn.png',
    answer1: false,
    answer2: false,
    answer3: false,
    answer4: false,
    answer5: false,
    answer6: false,
    answer7: false,
    answer8: false,
    answer9: true,
    answer10: false,
    answer11: false,
    answer12: false,
    answer13: false,
    answer14: false,
    answer15: false,
    answer16: false,
    answer17: false,
    answer18: false,
    answer19: false,
    answer20: false,
    answer21: false,
    answer22: false,
    answer23: false,
    answer24: false,
  },
];
export default function SaxoExercises(value) {
  return saxoNotes[value];
}
export const Validate = (
  {
    a1,
    a2,
    a3,
    a4,
    a5,
    a6,
    a7,
    a8,
    a9,
    a10,
    a11,
    a12,
    a13,
    a14,
    a15,
    a16,
    a17,
    a18,
    a19,
    a20,
    a21,
    a22,
    a23,
    a24,
  },
  value
) => {
  const {
    answer1,
    answer2,
    answer3,
    answer4,
    answer5,
    answer6,
    answer7,
    answer8,
    answer9,
    answer10,
    answer11,
    answer12,
    answer13,
    answer14,
    answer15,
    answer16,
    answer17,
    answer18,
    answer19,
    answer20,
    answer21,
    answer22,
    answer23,
    answer24,
  } = saxoNotes[value];
  return (
    answer1 === a1 &&
    answer2 === a2 &&
    answer3 === a3 &&
    answer4 === a4 &&
    answer5 === a5 &&
    answer6 === a6 &&
    answer7 === a7 &&
    answer8 === a8 &&
    answer9 === a9 &&
    answer10 === a10 &&
    answer11 === a11 &&
    answer12 === a12 &&
    answer13 === a13 &&
    answer14 === a14 &&
    answer15 === a15 &&
    answer16 === a16 &&
    answer17 === a17 &&
    answer18 === a18 &&
    answer19 === a19 &&
    answer20 === a20 &&
    answer21 === a21 &&
    answer22 === a22 &&
    answer23 === a23 &&
    answer24 === a24
  );
};
